import React from "react";

const MusicGenresOptions = (props) => {
    const options = [
        { text: "Rock", handler: () => { }, id: 1 },
        { text: "Metal", handler: () => { }, id: 2 },
        { text: "Enstrümantal Müzik", handler: () => { }, id: 3 },
        { text: "Pop", handler: () => { }, id: 4 },
        { text: "Halk Müziği", handler: () => { }, id: 5 },
        { text: "Blues/Caz", handler: () => { }, id: 6 },
        { text: "Tasavvuf", handler: () => { }, id: 7 },
        { text: "Hiphop/Rap", handler: () => { }, id: 8 },
        { text: "Elektronik Müzik", handler: () => { }, id: 9 },
        { text: "Punk", handler: () => { }, id: 10 },
    ];
    const handleOptionClick = (option) => {
        switch (option.id) {
            case 1:
                displayMessage("Rock müziğinin vazgeçilmezlerini senin için sıralamak isterim: Elektro Gitar konusunda Stratocaster, Telecaster veya Les Paul gibi popüler modelleri tercih edebilirsin. Kaliteli amplifikatör ve efekt pedallar önerebilirim. Bas Gitarda P-bass veya J-bass gibi modelleri önerebilirim. Bunun dışında davul setlerine bakabilirsin. Aynı zamanda güzel bir ses kartı almanı şiddetle tavsiye ederim. :)");
                break;
            case 2:
                displayMessage("Metal müziğiyle ilgili ekipman ve enstrüman seçeneklerini sıralamak isterim. Elektrik gitar konusunda, genellikle ağır tonlar ve hızlı riffler için modifiye edilmiş Les Paul, Flying V, SG veya Ibanez RG gibi gitarları tercih edebilirsin. Humbucker manyetik pikaplar ve sert teller kullanman da önemli. Ayrıca, yüksek distorsiyonlu amplifikatörler ve metal distorsiyon pedalı gibi efekt pedalları da öneririm. Bas gitarda uzun ölçekli, aktif bas devreli modeller tercih edebilir ve bas efekt pedallarıyla tonunu zenginleştirebilirsin. Davul seti olarak hızlı ve teknik çalmaya uygun bir set, çift pedal kullanımı da düşünebilirsin. Vokal mikrofonu olarak metal müziği için özel olarak tasarlanmış güçlü bir mikrofon seçimi ve vokal efektleri de önemli. Bazı metal türlerinde klavye veya synthesizer kullanımı da sıkça görülüyor, bu nedenle özel seslere ve efektlere sahip bir synth düşünebilirsin. Efekt pedalı olarak metal-distortion pedalları, noise gate'ler ve wah-wah pedalları gibi özel efektleri değerlendirebilirsin. Güçlü bir gitar amplifikatörü ve kaliteli hoparlörlerle birlikte çalmak da önemli. Son olarak, kayıt ekipmanı olarak bilgisayar tabanlı bir sistem, ses kartı, kaliteli mikrofonlar ve monitör hoparlörler kullanmanı öneririm. Her metal müzisyeni kendi tarzına göre özelleştirebileceği bir set-up oluşturabilir, bu nedenle kişisel tercihlerin ve yaratıcılığın ön planda olduğunu unutmaman önemli. Rock on! 🤘");
                break;
            case 3:
                displayMessage("Enstrümantal müzikle ilgilenen birisi için önemli olan enstrümanlar ve ekipmanları paylaşmak isterim: Elektrik gitar geniş tonal aralığı ve esnekliği nedeniyle sıkça tercih edilir.farklı efekt pedalları kullanımı, loop pedalı gibi ekipmanlarla zenginleştirilebilir. Akustik gitar tercihinde, parmak stilinde çalım veya düz tabanca tekniğine uygun modeller araştırılabilir. Piyano veya klavye kullanımı, enstrümantal parçalara duygusal bir derinlik katabilir; bu nedenle, çok yönlü ses ve efekt seçeneklerine sahip elektronik klavyeler tercih edilebilir. Diğer enstrüman seçenekleri arasında yaylı çalgılar, üflemeli çalgılar ve perküsyon bulunmaktadır. Ayrıca, kayıt ve prodüksiyon sürecinizi geliştirmek için bilgisayar tabanlı ses işleme yazılımları, kaliteli ses kartları ve MIDI kontrol cihazları gibi ekipmanları da düşünebilirsiniz. İhtiyaçlarınıza uygun bir ses kartı seçimi, kayıtlarınızı daha yüksek kalitede yapmanıza yardımcı olabilir. Müzikle kalın :)");
                break;
            case 4:
                displayMessage("Pop müziğiyle ilgilenen birisi için müzik enstrümanları ve ekipmanları hakkında bilgi vermek isterim: Elektrik gitar konusunda, pop şarkılarında yaygın olarak kullanılan temiz tonlar ve hafif efektler için Stratocaster, Telecaster veya Les Paul gibi popüler modelleri tercih edebilirsin. Klavye veya piyano, pop müziğin melodi ve harmoni yapısına katkı sağlayabilir; bu nedenle, elektronik klavyelerle farklı ses ve efekt seçeneklerini keşfetmek önerilir. Bas gitar, ritmi güçlendirmek ve alt frekansta destek sağlamak amacıyla kullanılabilir, bu nedenle P-bass veya J-bass gibi modeller pop müziğe uygun olabilir. Davul, ritmi oluşturmak ve şarkıya enerji katmak için önemlidir; bu noktada, elektronik davul setleri veya akustik davul setleri pop müziğin çeşitli alt türlerine uygun olabilir. Vokal mikrofonu olarak, pop müziğin vokal odaklı yapısını destekleyecek kaliteli bir mikrofon kullanımını öneririm. Bunun yanında, reverb, delay, chorus gibi hafif efektlerle sesi zenginleştirebilirsin. Kayıt ve prodüksiyon sürecini geliştirmek için bilgisayar tabanlı bir ses işleme (DAW) yazılımı, ses kartı, kaliteli monitör hoparlörler ve kulaklık kullanmanı tavsiye ederim. Bu ekipmanlar, pop müziği içinde çeşitli sesler ve prodüksiyon teknikleri oluşturmanıza yardımcı olabilir.Müzikle kalın :)");
                break;
            case 5:
                displayMessage("Türk halk müziğiyle ilgilenen birisi için önemli olan enstrümanlar ve ekipmanlar hakkında bilgi vermek isterim: Bağlama, geleneksel Türk müziğinin vazgeçilmez enstrümanlarından biridir. Farklı telli bağlama türleri arasında seçim yapabilir ve bölgesel farklılıklara uygun olarak çeşitli teknikleri öğrenebilirsin. Klasik Türk musikisi icraları için kullanılan kemençe de öne çıkan bir enstrümandır. Yaylı çalgılar arasında yer alır ve genellikle özel makamların ifadesinde kullanılır. Ud, Türk halk müziğinde yaygın olarak kullanılan bir saz türüdür. Yumuşak ve melodik tonlarıyla ön plana çıkar. Klarnet, üflemeli çalgılar arasında popülerdir ve özellikle fasıl müziği icralarında sıkça kullanılır. Türk halk müziğinde davul ve zurna takımı, ritmik vurguları güçlendirmek ve genellikle halk danslarına eşlik etmek amacıyla kullanılır. Bunun yanı sıra, kaliteli bir ses kaydı almanı sağlayacak mikrofonlar ve ses kartları gibi kayıt ekipmanlarına da ihtiyaç duyabilirsin. Her bir enstrümanın ve ekipmanın Türk halkmüziği içinde nasıl kullanılacağını anlamak, bu tarihi ve zengin müzik geleneğinin bir parçası olmanı sağlayacaktır.Müzikle kalın :)");
                break;
            case 6:
                displayMessage("Blues/caz müziğiyle ilgilenen birisi için enstrüman ve ekipman seçimi büyük önem taşır. Blues gitarlarında popüler olan Stratocaster ve Telecaster gibi modeller, humbucker veya single-coil manyetik pikaplarla kullanılır. Caz gitarları genellikle hollowbody veya semi-hollowbody modellerdir ve temiz tonlar için özel tonewood kullanımına dikkat edilir. Bas gitarda fretless veya P-bass gibi modeller tercih edilirken, roundwound teller kullanılır. Caz müziğin vazgeçilmezi olan saksofon ve trompet gibi üflemeliler, farklı tonlarıyla öne çıkar. Davul seti, swing ritimleri ve caz temposuna uygun varyasyonları çalmak adına seçilir. Piyano veya klavye, akorlar, melodiler ve ritmik öğeler için kullanılır. Kontrbas, caz müziğinin önemli bir enstrümanıdır. Kaliteli bir vokal mikrofonu, blues ve caz vokalleri için önemlidir. Efekt pedalları, müziğe karakter katmada kullanılırken, amplifikatör seçimi tonun belirlenmesinde kritiktir.Müzikle kalın :)");
                break;
            case 7:
                displayMessage("Tasavvuf müziğinin derin maneviyatını keşfetmek isteyenler için en uygun enstrümanları seçmek önemlidir. Ney, bu özel müzik türünün sembolüdür ve nefesle çalınan bu kamış flütü, müziğe derin bir ruhsallık katmaktadır. Ritmik vuruşlarıyla tasavvuf ritimlerini destekleyen Kudüm, darbuka benzeri bir davul olarak öne çıkar. Tanbur, tasavvuf müziğinde duygu yüklü tonlarıyla dikkat çeken üç telli bir saz enstrümanıdır. Mevlevi ayinlerinde sıkça kullanılan Keman, müziğe duygusal ve melankolik bir hava katar. Akustik zenginlik sunan tellere vurularak çalınan Kanun, tasavvuf müziğinin derinliklerini ifade etmede etkilidir. Göğüs üzerinde çalınan Rebab, duygu dolu ve mistik bir atmosfer yaratmada kullanılır. Vokal performanslar, tasavvuf müziğinde ayrı bir öneme sahiptir; Mevlevi ilahileri ve diğer eserlerde kaliteli vokal performanslar müziği güçlendirir. İlahi ve sema müziği icralarında sıklıkla tercih edilen Tambur, yaylı çalgılar arasında öne çıkar. Minimal ve akustik bir yaklaşım benimseyen tasavvuf müziği, kaliteli mikrofonlar ve ses kayıt ekipmanları kullanarak profesyonel ses kayıtları elde etmeyi hedefler. Performans sırasında uygun bir akustik ortam ve ses sistemi seçimi, müzikal deneyimi tamamlar.Müzikle kalın :) ");
                break;
            case 8:
                displayMessage("Hiphop müziğiyle ilgilenen birisi için müzik enstrümanları ve ekipmanlarına dair bazı önerilerde bulunmak isterim: Elektronik Davul Makineleri (EDM) ve sampling odaklı müzik üretimine ilgi duyuyorsan, bu alanda kullanabileceğin birçok enstrüman ve ekipman bulunmaktadır. Öncelikle, bilgisayar tabanlı bir ses işleme yazılımı (DAW) edinmeyi düşünebilirsin. DAW'lar, beat yapımı, ses kaydı ve düzenleme süreçlerini yönetmene yardımcı olur. Virtual Studio Technology (VST) ve Audio Units (AU) gibi eklenti formatları kullanarak çeşitli sanal enstrümanlar ve efektler ekleyebilirsin. Bu, özgün ve çeşitli sesler elde etmeni sağlar. Klavye veya MIDI kontrol cihazları, melodik ve ritmik öğeleri programlamanda veya canlı performanslarda kullanışlı olabilir. Drum pad'ler veya pad kontrol cihazları, ritim ve perküsyon unsurlarını geliştirmende etkili olabilir. Kaliteli bir ses kartı ve monitör hoparlörler, prodüksiyonunun ses kalitesini artırmak için önemlidir. Ayrıca, kulaklık kullanımı da detaylı ses kontrolü sağlamak açısından faydalı olabilir. Beatmaking ve sampling konusunda ileri seviye bir deneyim elde etmek istiyorsan, ses mühendisliği ve prodüksiyon konularında online kaynaklardan yararlanabilir veya ilgili kurslara katılabilirsin. Hiphop müziği, yaratıcılığa dayalı bir tür olduğu için kendi tarzını bulmak ve geliştirmek için sürekli deneme yanılma yapabilir ve kişisel ifadeni keşfetmeye odaklanabilirsin.Müzikle kalın :)");
                break;
            case 9:
                displayMessage("Elektronik müzikle ilgilenen birisi için, yaratıcılıklarını ifade etmeleri ve özgün sesler oluşturmaları için çeşitli enstrümanlar ve ekipmanlar bulunmaktadır. Temel enstrümanlardan biri olan synthesizer (sentezleyici), farklı sesleri üretmek ve manipüle etmek için kullanılırken, drum machine (davul makinesi) ritim oluşturmak için ideal bir araçtır. MIDI klavye, pad kontrol cihazları ve diğer MIDI tabanlı kontrol cihazları, müzikal performansı ve prodüksiyonu kolaylaştırmak üzere kullanılır. Digital Audios Workstation (DAW) adlı yazılımlar, bilgisayar üzerinde ses kaydı yapma, düzenleme ve prodüksiyon süreçlerini yönetmek için kullanılır. Samplers (örnekleyiciler), gerçek dünya seslerini kaydedip çeşitli şekillerde manipüle etmek için kullanılır. Effects processors (efekt işleme cihazları) ise reverb, delay, chorus gibi efektleri ekleyerek sesleri zenginleştirmek ve şekillendirmek amacıyla kullanılır. DJ kontrol cihazları, elektronik müziği canlı performanslar için mixleme ve DJ'lik yapmak için idealdir. Analog synths (analog sentezleyiciler), geleneksel analog ses üreten sintezleyicilerdir ve karakteristik, sıcak tonlarıyla bilinirler. Controller keyboards (kontrol klavyeleri) ise MIDI kontrollerle entegre çalışan klavyeler, melodi ve akorları çalmak için kullanılır. Bu ekipmanlarla birlikte yüksek kaliteli kulaklık ve monitör hoparlörler kullanarak ses kalitesini değerlendirmek mümkündür.Müzikle kalın :)");
                break;
            case 10:
                displayMessage("Punk müziğiyle ilgilenen birisi, enerji dolu ve hızlı tempolu bir müzik türünde çalmak için belirli enstrümanlar ve ekipmanları tercih edebilir. Elektrikli gitarlar, punk müziğin temelini oluşturur ve genellikle hızlı ve basit akorlarla güçlü riffleri çıkaran modeller tercih edilir, özellikle Stratocaster ve Telecaster gibi. Bas gitarlar, ritmi güçlendirmek ve melodiyi desteklemek amacıyla kullanılır, P-bass veya J-bass gibi modeller punk müzisyenleri arasında yaygındır. Davullar, punk müziğin enerjik ritimlerini oluşturmak için önemlidir ve genellikle basit ve hızlı vuruşlara uygun drum kitleri tercih edilir. Gitar ve bas gitarlar için yüksek enerjili ve bozuk tonlar üreten amplifikatörler, punk müziğin karakteristik sesini belirler. Vokallerin güçlü bir şekilde duyulmasını sağlamak için kaliteli mikrofonlar kullanılır ve çeşitli efekt pedalları, gitaristlere seslerini şekillendirme ve efektler eklemeleri için olanak tanır. Canlı performanslarda kullanılan bir ses sistemi (PA sistemi) ve gitara monteli geri bildirim önleyiciler, sahnede kontrolü sağlamak açısından önemlidir.Müzikle kalın :)");
                break;
            default:
                break;
        }
    };
    const displayMessage = (message) => {
        const chatbotMessage = props.createChatBotMessage(message);
        props.actionProvider.setChatbotMessage(chatbotMessage);
      };
    
      const buttonsMarkup = options.map((option) => (
        <button key={option.id} onClick={() => handleOptionClick(option)} className="option-button bg-61045F text-black py-2 px-3 rounded-full border-none cursor-pointer">
          {option.text}
        </button>
      ));
    
      return <div>{buttonsMarkup}</div>;
    };

export default MusicGenresOptions;
